rule Wallet_Stealer
{ 
meta: 
description = "Wallet Stealer Detector" 
author = "ThreatMon" 
date = "28/08/2023" 
strings: 
  str1="#Badreddine67  RU - DZ"
  str2="\\atomic\\Local Storage\\leveldb"
  str3="\\Exodus\\exodus.wallet"
  str4="\\com.liberty.jaxx\\IndexedDB\\file__0.indexeddb.leveldb"
  str5="\\Electrum\\wallets"
  str6="\\bytecoin"
  str7="\\Ethereum\\keystore"
  str8="\\Guarda\\Local Storage\\leveldb"
  str9="\\Coinomi\\Coinomi\\wallets"
  str10="\\Armory"
  str11="\\Zcash"
  str12="kmhcihpebfmpgmihbkipmjlmmioameka"
  str13="dngmlblcodfobpdpecaadgfbcggfjfnm"
  str14="aholpfdialjgjfhomihkjbmgjidlcdno"
  str15="fnjhmkhhmkbjkkabndcnnogagogbneec"
  str16="cnmamaachppnkjgnildpdmkaakejnhae"
  str17="fihkakfobkmkjojpchpfgcmhfjnmnfpi"
  str18="hpglfhgfnhbgpjdenjgmdgoeiappafln"
  str19="ffnbelfdoeiohenkjibnmadjiehjhajb"
  str20="nhnkbkgjikgcigadomkphalanndcapjk"
  str21="hnfanknocfeofbddgcijnmhnfnkdnaad"
  str22="afbcbjpbpfadlkmhmclhkeeodmamcflc"
  str23="kpfopkelmapcoipemfendmdcghnegimn"
  str24="jbdaocneiiinmjbjlgalhcelgbejmnid"
  str25="jojhfeoedkpkglbfimdfabpdfjaoolaf"
  str26="nknhiehlklippafakaeklbeglecifhad"
  str27="icmkfkmjoklfhlfdkkkgpnpldkgdmhoe"
  str28="dkdedlpgdmmkkfjabffeganieamfklkm"
  str29="cihmoadaighcejopammfbmddcmdekcje"
  str30="klnaejjgbibmhlephnhpmaofohgkpgkd"
  str31="bcopgchhojmggmffilplmbdicgaihlkp"
  str32="onofpnbbkehpmmoabgpcpmigafmmnjhl"
  str33="lkcjlnjfpbikmcmbachjpdbijejflpcm"
  str34="ijmpgkjfkbfhoebgogflfebnmejmfbml"
  str35="lodccjjbdhfakaekdiahmedfbieldgik"
  str36="nlgbhdfgdhgbiamfdfmbikcdghidoadd"
  str37="hcflpincpppdclinealmandijcmnkbgn"
  str38="flpiciilemghbmfalicajoolhkkenfel"
  str39="fhmfendgdocmcbmfikdcogofphimnkno"
  str40="dmkamcknogkgcdfhhbddcghachkejeap"
  str41="cphhlgmgameodnhkjdmkpanlelnlohao"
  str42="kncchdigobghenbbaddojjnnaogfppfj"
  str43="nlbmnnijcnlegkjjpcfjclmcfggfefdm"
  str44="aeachknmefphepccionboohckonoeemg"
  str45="fhbohimaelbohpjbbldcngcnapndodjp"
  str46="ibnejdfjmmkpcnlpebklmnkoeoihofec"
  str47="imloifkgjagghnncjkhggdhalmcnfklk"
  str48="admmjipmmciaobhojoghlmleefbicajg"
  str49="acmacodkjbdgmoleebolmdjonilkdbch"
condition: 
5 of ($str*)
}
